name: Cypress Tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [start-example-workflow]
env:
  TG_API_KEY: ${{ secrets.TG_API_KEY }}
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Запуск тестов
      - name: Run Cypress tests
        run: npx cypress run
        
      # Извлечение данных из отчета
      - name: Extract data from report
        run: |
          tests_passed=$(jq '.stats.tests' results/test-results.json)
          
      # Отправка сообщения в Telegram
      - name: Send message to Telegram
        env:
          TG_API_KEY: ${{ secrets.TG_API_KEY }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -X POST \
               -H 'Content-Type: application/json' \
               -d '{"chat_id": "'$CHAT_ID'", "text": "Тестирование завершено. Пройдено тестов: '$tests_passed'"}' \
               https://api.telegram.org/bot${TG_API_KEY}/sendMessage
